
// Mock data for products, categories, etc.
export interface User {
  id: string;
  name: string;
  email: string;
  role: 'buyer' | 'seller' | 'admin';
  avatar?: string;
}

export const currentUser: User = {
  id: 'user1',
  name: 'John Doe',
  email: 'john@example.com',
  role: 'buyer',
  avatar: '/placeholder.svg'
};

export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: string;
  rating: number;
  reviews: number;
  inStock: boolean;
  seller: string;
  status?: 'active' | 'pending' | 'rejected';
}

export interface LiveStream {
  id: string;
  title: string;
  sellerId: string;
  sellerName: string;
  sellerAvatar: string;
  thumbnailImage: string;
  isLive: boolean;
  viewers: number;
  startedAt: string;
  featuredProducts: string[]; // Product IDs
}

export const categories = [
  'Electronics',
  'Home & Kitchen',
  'Fashion',
  'Beauty & Personal Care',
  'Sports & Outdoors',
  'Books',
  'Toys & Games',
  'Furniture',
  'Jewelry',
  'Automotive',
  'Health',
  'Pet Supplies',
  'Garden & Outdoor',
  'Grocery',
  'Baby & Kids',
  'Office Supplies',
  'Music Instruments',
  'Arts & Crafts',
  'Tools & Home Improvement',
  'Computer & Accessories'
];

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Wireless Earbuds Pro',
    description: 'Experience crystal-clear sound with our latest wireless earbuds. Features active noise cancellation and 30-hour battery life.',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df',
    category: 'Electronics',
    rating: 4.5,
    reviews: 128,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p2',
    name: 'Smart Home Speaker',
    description: 'Control your home with voice commands. Compatible with most smart home devices and services.',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1543512214-318c7553f230',
    category: 'Electronics',
    rating: 4.2,
    reviews: 85,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p3',
    name: 'Ergonomic Office Chair',
    description: 'Work in comfort with this adjustable ergonomic chair. Features lumbar support and breathable mesh back.',
    price: 199.99,
    image: 'https://images.unsplash.com/photo-1595515106865-dd46de49f026',
    category: 'Furniture',
    rating: 4.7,
    reviews: 42,
    inStock: false,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p4',
    name: 'Stainless Steel Water Bottle',
    description: 'Stay hydrated with this insulated water bottle. Keeps drinks cold for 24 hours or hot for 12 hours.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1620176512090-a4952217818e',
    category: 'Sports & Outdoors',
    rating: 4.8,
    reviews: 156,
    inStock: true,
    seller: 'StyleHub',
    status: 'active'
  },
  {
    id: 'p5',
    name: 'Organic Cotton T-Shirt',
    description: 'Comfortable, sustainable, and stylish. Made from 100% organic cotton with eco-friendly dyes.',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27',
    category: 'Fashion',
    rating: 4.3,
    reviews: 67,
    inStock: true,
    seller: 'StyleHub',
    status: 'active'
  },
  {
    id: 'p6',
    name: 'Smart Fitness Tracker Watch',
    description: 'Track your workouts, heart rate, and sleep patterns. Water-resistant and long battery life.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b1',
    category: 'Electronics',
    rating: 4.4,
    reviews: 94,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p7',
    name: 'Non-Stick Cooking Pot Set',
    description: 'Complete set of non-stick pots and pans. Dishwasher safe and PFOA-free.',
    price: 149.99,
    image: 'https://images.unsplash.com/photo-1584453147784-13c4432293ba',
    category: 'Home & Kitchen',
    rating: 4.6,
    reviews: 38,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p8',
    name: 'Portable Bluetooth Speaker',
    description: 'Portable speaker with rich sound and deep bass. Waterproof and 12 hours of playtime.',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1',
    category: 'Electronics',
    rating: 4.1,
    reviews: 112,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p9',
    name: 'Professional DSLR Camera',
    description: 'Capture stunning photos with this high-quality DSLR camera. Features 24.2 megapixels and 4K video recording.',
    price: 799.99,
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32',
    category: 'Electronics',
    rating: 4.9,
    reviews: 75,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p10',
    name: 'Leather Wallet for Men',
    description: 'Genuine leather wallet with multiple card slots and RFID blocking technology.',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93',
    category: 'Fashion',
    rating: 4.5,
    reviews: 88,
    inStock: true,
    seller: 'StyleHub',
    status: 'active'
  },
  {
    id: 'p11',
    name: 'Essential Oil Diffuser',
    description: 'Ultrasonic diffuser with 7 LED light options and automatic shut-off feature.',
    price: 32.99,
    image: 'https://images.unsplash.com/photo-1608571423539-e951a27ea9e8',
    category: 'Home & Kitchen',
    rating: 4.6,
    reviews: 127,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p12',
    name: 'Yoga Mat Non-Slip',
    description: 'Eco-friendly yoga mat with alignment marks and excellent grip. Includes carrying strap.',
    price: 45.99,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b',
    category: 'Sports & Outdoors',
    rating: 4.7,
    reviews: 62,
    inStock: true,
    seller: 'SportActive',
    status: 'active'
  },
  {
    id: 'p13',
    name: 'Ceramic Coffee Mug Set',
    description: 'Set of 6 ceramic mugs in assorted colors. Microwave and dishwasher safe.',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1509785307050-d4066910ec1e',
    category: 'Home & Kitchen',
    rating: 4.3,
    reviews: 45,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p14',
    name: 'Mechanical Gaming Keyboard',
    description: 'RGB backlit mechanical keyboard with customizable keys and anti-ghosting technology.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef',
    category: 'Computer & Accessories',
    rating: 4.8,
    reviews: 134,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p15',
    name: 'Facial Cleansing Brush',
    description: 'Gentle exfoliation with silicone bristles. Waterproof and rechargeable.',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1626784215002-774870fedcd5',
    category: 'Beauty & Personal Care',
    rating: 4.4,
    reviews: 89,
    inStock: true,
    seller: 'BeautyZone',
    status: 'active'
  },
  {
    id: 'p16',
    name: 'Wooden Chess Set',
    description: 'Hand-crafted wooden chess set with felt-lined storage drawer.',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1586165368502-1bad197a6461',
    category: 'Toys & Games',
    rating: 4.7,
    reviews: 32,
    inStock: true,
    seller: 'GameMaster',
    status: 'active'
  },
  {
    id: 'p17',
    name: 'Wireless Charging Pad',
    description: 'Fast-charging wireless pad compatible with all Qi-enabled devices.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1618577914033-0f35a4ee8fd4',
    category: 'Electronics',
    rating: 4.2,
    reviews: 116,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p18',
    name: 'Leather Crossbody Bag',
    description: 'Genuine leather crossbody bag with adjustable strap and multiple compartments.',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1548863227-3af567fc3b27',
    category: 'Fashion',
    rating: 4.6,
    reviews: 78,
    inStock: true,
    seller: 'StyleHub',
    status: 'active'
  },
  {
    id: 'p19',
    name: 'Dutch Oven Cast Iron',
    description: 'Pre-seasoned cast iron Dutch oven for perfect slow-cooking and baking.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1551371816-425137def4e2',
    category: 'Home & Kitchen',
    rating: 4.9,
    reviews: 54,
    inStock: true,
    seller: 'ChefChoice',
    status: 'active'
  },
  {
    id: 'p20',
    name: 'Indoor Plant Monstera',
    description: 'Low-maintenance indoor tropical plant in decorative pot.',
    price: 35.99,
    image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b',
    category: 'Garden & Outdoor',
    rating: 4.5,
    reviews: 41,
    inStock: true,
    seller: 'GreenThumb',
    status: 'active'
  },
  {
    id: 'p21',
    name: 'Digital Drawing Tablet',
    description: 'Pressure-sensitive drawing tablet with wireless pen. Perfect for digital artists.',
    price: 149.99,
    image: 'https://images.unsplash.com/photo-1563206767-5b18f218e8de',
    category: 'Computer & Accessories',
    rating: 4.7,
    reviews: 93,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p22',
    name: 'Bestseller Novel Collection',
    description: 'Set of 5 bestselling novels from award-winning authors.',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353',
    category: 'Books',
    rating: 4.8,
    reviews: 47,
    inStock: true,
    seller: 'BookWorm',
    status: 'active'
  },
  {
    id: 'p23',
    name: 'Retro Vinyl Record Player',
    description: 'Modern turntable with vintage design. Includes Bluetooth connectivity.',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1519677584237-752f8853252e',
    category: 'Music Instruments',
    rating: 4.3,
    reviews: 68,
    inStock: true,
    seller: 'MusicLovers',
    status: 'active'
  },
  {
    id: 'p24',
    name: 'Silver Hoop Earrings',
    description: 'Sterling silver hoop earrings with hypoallergenic posts.',
    price: 42.99,
    image: 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d',
    category: 'Jewelry',
    rating: 4.6,
    reviews: 82,
    inStock: true,
    seller: 'GemGallery',
    status: 'active'
  },
  {
    id: 'p25',
    name: 'Organic Skincare Set',
    description: 'Complete skincare routine with all-natural ingredients. Includes cleanser, toner, and moisturizer.',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881',
    category: 'Beauty & Personal Care',
    rating: 4.7,
    reviews: 63,
    inStock: true,
    seller: 'BeautyZone',
    status: 'active'
  },
  {
    id: 'p26',
    name: 'Electric Stand Mixer',
    description: 'Powerful stand mixer with 5-quart bowl and multiple attachments.',
    price: 249.99,
    image: 'https://images.unsplash.com/photo-1599493356626-9fdbdabfd9bd',
    category: 'Home & Kitchen',
    rating: 4.9,
    reviews: 107,
    inStock: true,
    seller: 'ChefChoice',
    status: 'active'
  },
  {
    id: 'p27',
    name: 'Wireless Gaming Mouse',
    description: 'Ergonomic gaming mouse with adjustable DPI and programmable buttons.',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7',
    category: 'Computer & Accessories',
    rating: 4.6,
    reviews: 95,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p28',
    name: 'Cotton Bath Towel Set',
    description: 'Set of 4 plush, absorbent cotton bath towels in assorted colors.',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1565625736543-6be63a5dcfe0',
    category: 'Home & Kitchen',
    rating: 4.5,
    reviews: 59,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p29',
    name: 'Mountain Bike Helmet',
    description: 'Lightweight bike helmet with adjustable fit and enhanced ventilation.',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1557803056-bfda4d972c25',
    category: 'Sports & Outdoors',
    rating: 4.8,
    reviews: 43,
    inStock: true,
    seller: 'SportActive',
    status: 'active'
  },
  {
    id: 'p30',
    name: 'LED Desk Lamp with USB Port',
    description: 'Adjustable LED desk lamp with brightness levels and built-in USB charging port.',
    price: 35.99,
    image: 'https://images.unsplash.com/photo-1534381734037-ced371adeeb8',
    category: 'Office Supplies',
    rating: 4.4,
    reviews: 84,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p31',
    name: 'Stainless Steel Kitchen Knife Set',
    description: 'Professional-grade knife set with wooden block. Includes 12 pieces.',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1593618998160-e34014e67546',
    category: 'Home & Kitchen',
    rating: 4.7,
    reviews: 76,
    inStock: true,
    seller: 'ChefChoice',
    status: 'active'
  },
  {
    id: 'p32',
    name: 'Baby Sleep Monitor',
    description: 'Video baby monitor with night vision and two-way audio communication.',
    price: 119.99,
    image: 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac',
    category: 'Baby & Kids',
    rating: 4.8,
    reviews: 52,
    inStock: true,
    seller: 'BabyWorld',
    status: 'active'
  },
  {
    id: 'p33',
    name: 'Automatic Pet Feeder',
    description: 'Programmable pet feeder with portion control and voice recording.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119',
    category: 'Pet Supplies',
    rating: 4.5,
    reviews: 64,
    inStock: true,
    seller: 'PetLover',
    status: 'active'
  },
  {
    id: 'p34',
    name: 'Classic Wristwatch',
    description: 'Elegant analog watch with leather strap and stainless steel case.',
    price: 149.99,
    image: 'https://images.unsplash.com/photo-1539874754764-5a96559165b0',
    category: 'Fashion',
    rating: 4.6,
    reviews: 87,
    inStock: true,
    seller: 'StyleHub',
    status: 'active'
  },
  {
    id: 'p35',
    name: 'Wireless Doorbell Camera',
    description: 'Smart doorbell with HD video, motion detection, and smartphone notifications.',
    price: 169.99,
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827',
    category: 'Tools & Home Improvement',
    rating: 4.7,
    reviews: 98,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p36',
    name: 'Acrylic Paint Set',
    description: '24 vibrant colors with 3 paint brushes. Non-toxic and quick-drying.',
    price: 27.99,
    image: 'https://images.unsplash.com/photo-1578070181910-f1e514afdd08',
    category: 'Arts & Crafts',
    rating: 4.5,
    reviews: 39,
    inStock: true,
    seller: 'ArtSupplies',
    status: 'active'
  },
  {
    id: 'p37',
    name: 'Car Phone Mount',
    description: 'Universal car phone holder with dashboard and air vent mounting options.',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1617124544034-4fa151cd7877',
    category: 'Automotive',
    rating: 4.3,
    reviews: 112,
    inStock: true,
    seller: 'AutoParts',
    status: 'active'
  },
  {
    id: 'p38',
    name: 'Protein Powder Supplement',
    description: 'Natural whey protein powder with 25g protein per serving. No artificial flavors.',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d',
    category: 'Health',
    rating: 4.6,
    reviews: 73,
    inStock: true,
    seller: 'HealthyLife',
    status: 'active'
  },
  {
    id: 'p39',
    name: 'Hiking Backpack 40L',
    description: 'Waterproof hiking backpack with multiple compartments and padded straps.',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1622560480654-d96214fdc887',
    category: 'Sports & Outdoors',
    rating: 4.7,
    reviews: 58,
    inStock: true,
    seller: 'SportActive',
    status: 'active'
  },
  {
    id: 'p40',
    name: 'Wooden Coffee Table',
    description: 'Mid-century modern coffee table with solid wood legs and glass top.',
    price: 199.99,
    image: 'https://images.unsplash.com/photo-1592078615290-033ee584e267',
    category: 'Furniture',
    rating: 4.6,
    reviews: 45,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p41',
    name: 'Wireless Router',
    description: 'Dual-band WiFi router with gigabit speeds and excellent coverage.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1623282033815-40b05d96c903',
    category: 'Computer & Accessories',
    rating: 4.5,
    reviews: 91,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p42',
    name: 'Electric Toothbrush',
    description: 'Rechargeable sonic toothbrush with multiple cleaning modes and timer.',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1559591934-75c8110b811e',
    category: 'Beauty & Personal Care',
    rating: 4.7,
    reviews: 124,
    inStock: true,
    seller: 'BeautyZone',
    status: 'active'
  },
  {
    id: 'p43',
    name: 'Handmade Ceramic Vase',
    description: 'Unique handcrafted ceramic vase. Each piece has slight variations in color and texture.',
    price: 45.99,
    image: 'https://images.unsplash.com/photo-1612196808214-b7e369780cd0',
    category: 'Home & Kitchen',
    rating: 4.8,
    reviews: 37,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p44',
    name: 'Puzzle Set 1000 Pieces',
    description: 'Beautiful landscape puzzle for hours of entertainment. High-quality interlocking pieces.',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1618513648040-d473587a5018',
    category: 'Toys & Games',
    rating: 4.4,
    reviews: 62,
    inStock: true,
    seller: 'GameMaster',
    status: 'active'
  },
  {
    id: 'p45',
    name: 'Wireless Noise-Canceling Headphones',
    description: 'Over-ear headphones with active noise cancellation and 30 hours of battery life.',
    price: 159.99,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b',
    category: 'Electronics',
    rating: 4.9,
    reviews: 146,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p46',
    name: 'Gourmet Chocolate Box',
    description: 'Assortment of handmade chocolates with different fillings and flavors.',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b',
    category: 'Grocery',
    rating: 4.8,
    reviews: 53,
    inStock: true,
    seller: 'GourmetEats',
    status: 'active'
  },
  {
    id: 'p47',
    name: 'Premium Yoga Block Set',
    description: 'Set of 2 high-density foam yoga blocks with non-slip surface.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1593164842249-d74fc06dae05',
    category: 'Sports & Outdoors',
    rating: 4.5,
    reviews: 48,
    inStock: true,
    seller: 'SportActive',
    status: 'active'
  },
  {
    id: 'p48',
    name: 'LED Plant Grow Light',
    description: 'Full-spectrum plant grow light with timer and adjustable gooseneck.',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1633869699811-593c866a94e4',
    category: 'Garden & Outdoor',
    rating: 4.6,
    reviews: 67,
    inStock: true,
    seller: 'GreenThumb',
    status: 'active'
  },
  {
    id: 'p49',
    name: 'Stainless Steel Travel Mug',
    description: 'Double-wall insulated travel mug that keeps drinks hot or cold for hours.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1590014496077-21532fecded0',
    category: 'Home & Kitchen',
    rating: 4.7,
    reviews: 83,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p50',
    name: 'Digital Kitchen Scale',
    description: 'Precise food scale with LCD display and multiple measurement units.',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1622480916113-9000ac49b79d',
    category: 'Home & Kitchen',
    rating: 4.5,
    reviews: 72,
    inStock: true,
    seller: 'ChefChoice',
    status: 'active'
  },
  // Adding 50 more products to reach 100 total
  {
    id: 'p51',
    name: 'Leather Desk Pad Protector',
    description: 'Premium PU leather desk mat for your workspace. Waterproof and non-slip.',
    price: 35.99,
    image: 'https://images.unsplash.com/photo-1593642634524-b40b5baae6bb',
    category: 'Office Supplies',
    rating: 4.3,
    reviews: 58,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p52',
    name: 'Air Purifier with HEPA Filter',
    description: 'Quiet operation air purifier that removes 99.97% of airborne particles.',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1585157603224-de96042c92e6',
    category: 'Home & Kitchen',
    rating: 4.8,
    reviews: 105,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p53',
    name: 'Acoustic Guitar',
    description: 'Full-size dreadnought acoustic guitar with solid spruce top.',
    price: 199.99,
    image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1',
    category: 'Music Instruments',
    rating: 4.6,
    reviews: 42,
    inStock: true,
    seller: 'MusicLovers',
    status: 'active'
  },
  {
    id: 'p54',
    name: 'Organic Green Tea Collection',
    description: 'Assortment of premium organic green teas from different regions.',
    price: 32.99,
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9',
    category: 'Grocery',
    rating: 4.7,
    reviews: 63,
    inStock: true,
    seller: 'GourmetEats',
    status: 'active'
  },
  {
    id: 'p55',
    name: 'Winter Wool Beanie',
    description: 'Warm knitted beanie with soft fleece lining. One size fits most.',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9',
    category: 'Fashion',
    rating: 4.5,
    reviews: 87,
    inStock: true,
    seller: 'StyleHub',
    status: 'active'
  },
  {
    id: 'p56',
    name: 'Gardening Tool Set',
    description: '8-piece garden tool set with carrying case. Includes pruners, trowel, rake, and more.',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1617228069096-4638a7ffc379',
    category: 'Garden & Outdoor',
    rating: 4.6,
    reviews: 39,
    inStock: true,
    seller: 'GreenThumb',
    status: 'active'
  },
  {
    id: 'p57',
    name: 'Laser Printer Monochrome',
    description: 'Fast monochrome laser printer with automatic duplex printing.',
    price: 179.99,
    image: 'https://images.unsplash.com/photo-1612815291583-648be8dc2d77',
    category: 'Office Supplies',
    rating: 4.4,
    reviews: 76,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p58',
    name: 'External Hard Drive 1TB',
    description: 'Portable external hard drive with USB 3.0 for fast data transfer.',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1531492746076-161ca9bcad58',
    category: 'Computer & Accessories',
    rating: 4.7,
    reviews: 94,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p59',
    name: 'Cedar Wooden Cutting Board',
    description: 'Handcrafted cedar cutting board with juice groove and non-slip feet.',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1594242389122-501485c99b06',
    category: 'Home & Kitchen',
    rating: 4.8,
    reviews: 53,
    inStock: true,
    seller: 'ChefChoice',
    status: 'active'
  },
  {
    id: 'p60',
    name: 'LED Selfie Ring Light',
    description: '10-inch ring light with adjustable brightness levels and phone holder.',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006',
    category: 'Electronics',
    rating: 4.3,
    reviews: 112,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p61',
    name: 'Aromatherapy Candle Set',
    description: 'Set of 3 scented candles made with natural soy wax and essential oils.',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1603006905393-c3cba527ab86',
    category: 'Home & Kitchen',
    rating: 4.6,
    reviews: 67,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p62',
    name: 'Dog Chew Toy Bundle',
    description: 'Set of 5 durable dog toys for small to medium-sized dogs.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1529472119196-cb724127a98e',
    category: 'Pet Supplies',
    rating: 4.5,
    reviews: 48,
    inStock: true,
    seller: 'PetLover',
    status: 'active'
  },
  {
    id: 'p63',
    name: '4K Action Camera',
    description: 'Waterproof action camera with 4K video recording and image stabilization.',
    price: 119.99,
    image: 'https://images.unsplash.com/photo-1613243555988-441166d4d6fd',
    category: 'Electronics',
    rating: 4.7,
    reviews: 85,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p64',
    name: 'Glass Food Storage Containers',
    description: 'Set of 5 glass containers with airtight lids. Microwave and freezer safe.',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1622486023148-fe5b07576176',
    category: 'Home & Kitchen',
    rating: 4.6,
    reviews: 73,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p65',
    name: 'Children\'s Educational Tablet',
    description: 'Kid-friendly tablet with parental controls and educational apps.',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1588077620420-9a7ce57bbf7f',
    category: 'Baby & Kids',
    rating: 4.5,
    reviews: 59,
    inStock: true,
    seller: 'BabyWorld',
    status: 'active'
  },
  {
    id: 'p66',
    name: 'Electric Milk Frother',
    description: 'Battery-operated handheld milk frother for coffee, lattes, and cappuccinos.',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1659417391350-bbc0a9c19fd9',
    category: 'Home & Kitchen',
    rating: 4.3,
    reviews: 97,
    inStock: true,
    seller: 'ChefChoice',
    status: 'active'
  },
  {
    id: 'p67',
    name: 'Running Shoes',
    description: 'Lightweight running shoes with responsive cushioning and breathable mesh.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a',
    category: 'Sports & Outdoors',
    rating: 4.7,
    reviews: 124,
    inStock: true,
    seller: 'SportActive',
    status: 'active'
  },
  {
    id: 'p68',
    name: 'Multivitamin Supplements',
    description: '90-day supply of essential vitamins and minerals for daily health support.',
    price: 28.99,
    image: 'https://images.unsplash.com/photo-1577174881658-0f30ed549adc',
    category: 'Health',
    rating: 4.5,
    reviews: 87,
    inStock: true,
    seller: 'HealthyLife',
    status: 'active'
  },
  {
    id: 'p69',
    name: 'Solar Garden Lights',
    description: 'Set of 8 solar-powered pathway lights. No wiring required.',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1568907700751-4b01de857252',
    category: 'Garden & Outdoor',
    rating: 4.4,
    reviews: 63,
    inStock: true,
    seller: 'GreenThumb',
    status: 'active'
  },
  {
    id: 'p70',
    name: 'Silk Pillowcase Set',
    description: 'Set of 2 pure mulberry silk pillowcases. Great for hair and skin.',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1629949009710-2332975471d2',
    category: 'Home & Kitchen',
    rating: 4.8,
    reviews: 72,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p71',
    name: 'DIY Craft Kit for Kids',
    description: 'Creative crafting kit with 150+ pieces for children aged 6-12.',
    price: 32.99,
    image: 'https://images.unsplash.com/photo-1609710228159-0fa9bd7c0827',
    category: 'Arts & Crafts',
    rating: 4.5,
    reviews: 46,
    inStock: true,
    seller: 'ArtSupplies',
    status: 'active'
  },
  {
    id: 'p72',
    name: 'Compact Digital Camera',
    description: '20MP digital camera with 5x optical zoom and HD video recording.',
    price: 149.99,
    image: 'https://images.unsplash.com/photo-1607462109225-6b64ae2dd3cb',
    category: 'Electronics',
    rating: 4.6,
    reviews: 84,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p73',
    name: 'Wooden Wine Rack',
    description: 'Countertop wine rack that holds 12 bottles. Elegant pine wood construction.',
    price: 35.99,
    image: 'https://images.unsplash.com/photo-1462887749044-b47cb05b83b8',
    category: 'Home & Kitchen',
    rating: 4.4,
    reviews: 52,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p74',
    name: 'Board Game Collection',
    description: 'Set of 3 classic family board games in vintage-style packaging.',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09',
    category: 'Toys & Games',
    rating: 4.7,
    reviews: 39,
    inStock: true,
    seller: 'GameMaster',
    status: 'active'
  },
  {
    id: 'p75',
    name: 'Bluetooth Car Adapter',
    description: 'Add Bluetooth functionality to any car with an AUX input.',
    price: 22.99,
    image: 'https://images.unsplash.com/photo-1619761216923-b1a33e04f6e8',
    category: 'Automotive',
    rating: 4.3,
    reviews: 105,
    inStock: true,
    seller: 'AutoParts',
    status: 'active'
  },
  {
    id: 'p76',
    name: 'Crystal Wine Glasses',
    description: 'Set of 4 hand-blown crystal wine glasses. Dishwasher safe.',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1609951651187-3109ca387634',
    category: 'Home & Kitchen',
    rating: 4.8,
    reviews: 47,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p77',
    name: 'Adjustable Dumbbell Set',
    description: 'Space-saving adjustable dumbbells that replace 15 sets of weights.',
    price: 199.99,
    image: 'https://images.unsplash.com/photo-1599058917212-d750089bc07e',
    category: 'Sports & Outdoors',
    rating: 4.9,
    reviews: 78,
    inStock: true,
    seller: 'SportActive',
    status: 'active'
  },
  {
    id: 'p78',
    name: 'Handcrafted Leather Journal',
    description: 'Vintage-style leather journal with refillable pages. Perfect gift for writers.',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1589998059171-988d887df646',
    category: 'Office Supplies',
    rating: 4.6,
    reviews: 64,
    inStock: true,
    seller: 'ArtSupplies',
    status: 'active'
  },
  {
    id: 'p79',
    name: 'Espresso Machine',
    description: '15-bar pump espresso and cappuccino maker with milk frother.',
    price: 179.99,
    image: 'https://images.unsplash.com/photo-1570347929626-2bbd1f2c3f53',
    category: 'Home & Kitchen',
    rating: 4.7,
    reviews: 92,
    inStock: true,
    seller: 'ChefChoice',
    status: 'active'
  },
  {
    id: 'p80',
    name: 'Beard Grooming Kit',
    description: 'Complete beard care set with scissors, comb, brush, oil, and balm.',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1621607150902-38b01b0dc5a3',
    category: 'Beauty & Personal Care',
    rating: 4.5,
    reviews: 77,
    inStock: true,
    seller: 'BeautyZone',
    status: 'active'
  },
  {
    id: 'p81',
    name: 'Portable Bluetooth Speaker',
    description: 'Waterproof Bluetooth speaker with 24-hour battery life and built-in microphone.',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1589003077984-894e762f8919',
    category: 'Electronics',
    rating: 4.6,
    reviews: 118,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p82',
    name: 'Natural Soy Wax Candle',
    description: 'Long-burning soy wax candle in recycled glass container. 60+ hours of burn time.',
    price: 22.99,
    image: 'https://images.unsplash.com/photo-1602874801007-bfcc00e48996',
    category: 'Home & Kitchen',
    rating: 4.4,
    reviews: 56,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p83',
    name: 'Indoor Cycling Bike',
    description: 'Quiet magnetic resistance exercise bike with LCD monitor and iPad holder.',
    price: 399.99,
    image: 'https://images.unsplash.com/photo-1591741977468-6f08fb7172d7',
    category: 'Sports & Outdoors',
    rating: 4.8,
    reviews: 83,
    inStock: true,
    seller: 'SportActive',
    status: 'active'
  },
  {
    id: 'p84',
    name: 'Premium Loose Leaf Tea Set',
    description: 'Collection of 8 gourmet loose leaf teas with infuser and storage tins.',
    price: 45.99,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3',
    category: 'Grocery',
    rating: 4.7,
    reviews: 42,
    inStock: true,
    seller: 'GourmetEats',
    status: 'active'
  },
  {
    id: 'p85',
    name: 'Leather Laptop Sleeve',
    description: 'Genuine leather sleeve for 15-inch laptops with magnetic closure.',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1603899968034-6939ecc41afc',
    category: 'Computer & Accessories',
    rating: 4.6,
    reviews: 69,
    inStock: true,
    seller: 'StyleHub',
    status: 'active'
  },
  {
    id: 'p86',
    name: 'Cat Climbing Tree',
    description: 'Multi-level cat tower with scratching posts, hammock, and toys.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1598755257130-c2aaca1f061c',
    category: 'Pet Supplies',
    rating: 4.5,
    reviews: 73,
    inStock: true,
    seller: 'PetLover',
    status: 'active'
  },
  {
    id: 'p87',
    name: 'Automatic Pasta Maker',
    description: 'Electric pasta machine that mixes, kneads, and extrudes fresh pasta.',
    price: 149.99,
    image: 'https://images.unsplash.com/photo-1602296751203-bd1a582bb645',
    category: 'Home & Kitchen',
    rating: 4.7,
    reviews: 58,
    inStock: true,
    seller: 'ChefChoice',
    status: 'active'
  },
  {
    id: 'p88',
    name: 'Diamond Stud Earrings',
    description: '0.5-carat total weight diamond studs in 14k white gold settings.',
    price: 499.99,
    image: 'https://images.unsplash.com/photo-1617038220319-276d3cfab638',
    category: 'Jewelry',
    rating: 4.9,
    reviews: 37,
    inStock: true,
    seller: 'GemGallery',
    status: 'active'
  },
  {
    id: 'p89',
    name: 'Smart Door Lock',
    description: 'Keyless entry door lock with fingerprint, code, and app access.',
    price: 159.99,
    image: 'https://images.unsplash.com/photo-1582619851427-ab4df8514fed',
    category: 'Tools & Home Improvement',
    rating: 4.6,
    reviews: 87,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p90',
    name: 'Bamboo Cutting Board Set',
    description: 'Set of 3 bamboo cutting boards in different sizes with juice grooves.',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1598003012278-4ccb4d836b8c',
    category: 'Home & Kitchen',
    rating: 4.5,
    reviews: 64,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p91',
    name: 'Cordless Drill Kit',
    description: '20V cordless drill with battery, charger, and 30-piece accessory set.',
    price: 99.99,
    image: 'https://images.unsplash.com/photo-1643114673614-46c230be71b3',
    category: 'Tools & Home Improvement',
    rating: 4.7,
    reviews: 95,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p92',
    name: 'Watercolor Paint Set',
    description: '36 vibrant colors with 12 artist-quality brushes and paper pad.',
    price: 47.99,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f',
    category: 'Arts & Crafts',
    rating: 4.6,
    reviews: 53,
    inStock: true,
    seller: 'ArtSupplies',
    status: 'active'
  },
  {
    id: 'p93',
    name: 'Wireless Earbuds with Case',
    description: 'True wireless earbuds with charging case providing 24 hours of playtime.',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1606131731446-5568d87113aa',
    category: 'Electronics',
    rating: 4.4,
    reviews: 138,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p94',
    name: 'Organic Cotton Baby Clothes',
    description: '5-piece set of organic cotton baby clothes. Sizes 0-3 months.',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1596870230774-54e74c793042',
    category: 'Baby & Kids',
    rating: 4.8,
    reviews: 42,
    inStock: true,
    seller: 'BabyWorld',
    status: 'active'
  },
  {
    id: 'p95',
    name: 'Car Dashboard Camera',
    description: 'HD dash cam with night vision and parking mode for vehicle security.',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1520340356584-f9917d1eea6f',
    category: 'Automotive',
    rating: 4.5,
    reviews: 76,
    inStock: true,
    seller: 'AutoParts',
    status: 'active'
  },
  {
    id: 'p96',
    name: 'Memory Foam Mattress Topper',
    description: '3-inch thick memory foam mattress topper for queen-sized beds.',
    price: 119.99,
    image: 'https://images.unsplash.com/photo-1583626018214-33bd28ca5919',
    category: 'Home & Kitchen',
    rating: 4.7,
    reviews: 108,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  },
  {
    id: 'p97',
    name: 'Robot Vacuum Cleaner',
    description: 'Smart robot vacuum with mapping technology and app control.',
    price: 249.99,
    image: 'https://images.unsplash.com/photo-1563163447-6984b4cfbaa2',
    category: 'Home & Kitchen',
    rating: 4.6,
    reviews: 135,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p98',
    name: 'Wooden Chess and Checkers Set',
    description: 'Reversible game board with storage drawer for chess and checkers pieces.',
    price: 54.99,
    image: 'https://images.unsplash.com/photo-1586165368502-1bad197a6461',
    category: 'Toys & Games',
    rating: 4.5,
    reviews: 47,
    inStock: true,
    seller: 'GameMaster',
    status: 'active'
  },
  {
    id: 'p99',
    name: 'Smartphone Gimbal Stabilizer',
    description: '3-axis stabilizer for smartphones with tracking and gesture control.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1619961602105-16fa2a5465c2',
    category: 'Electronics',
    rating: 4.7,
    reviews: 83,
    inStock: true,
    seller: 'TechGadgets',
    status: 'active'
  },
  {
    id: 'p100',
    name: 'Insulated Picnic Basket',
    description: 'Complete picnic set for 4 with insulated compartment and utensils.',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1575218823251-f9d243b6f720',
    category: 'Garden & Outdoor',
    rating: 4.4,
    reviews: 56,
    inStock: true,
    seller: 'HomeOffice',
    status: 'active'
  }
];

// Sample order statuses for profile page
export const orderStatuses = [
  { key: 'to-pay', label: 'Unpaid', count: 2, route: '/orders/unpaid' },
  { key: 'to-ship', label: 'Packed', count: 3, route: '/orders/packed' },
  { key: 'to-receive', label: 'Shipped', count: 1, route: '/orders/shipped' },
  { key: 'to-review', label: 'Rate', count: 4, route: '/orders/rate' }
];

// Mock LiveStreams data
export const mockLiveStreams: LiveStream[] = [
  {
    id: 'ls1',
    title: 'Latest Electronics Demo',
    sellerId: 'seller1',
    sellerName: 'TechGadgets',
    sellerAvatar: '/placeholder.svg',
    thumbnailImage: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df',
    isLive: true,
    viewers: 245,
    startedAt: new Date(Date.now() - 35 * 60000).toISOString(), // 35 minutes ago
    featuredProducts: ['p1', 'p2', 'p6', 'p8']
  },
  {
    id: 'ls2',
    title: 'Summer Fashion Collection',
    sellerId: 'seller2',
    sellerName: 'StyleHub',
    sellerAvatar: '/placeholder.svg',
    thumbnailImage: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27',
    isLive: true,
    viewers: 187,
    startedAt: new Date(Date.now() - 15 * 60000).toISOString(), // 15 minutes ago
    featuredProducts: ['p4', 'p5']
  },
  {
    id: 'ls3',
    title: 'Kitchen Essentials Demo',
    sellerId: 'seller3',
    sellerName: 'HomeOffice',
    sellerAvatar: '/placeholder.svg',
    thumbnailImage: 'https://images.unsplash.com/photo-1584453147784-13c4432293ba',
    isLive: false, // scheduled
    viewers: 0,
    startedAt: new Date(Date.now() + 120 * 60000).toISOString(), // 2 hours from now
    featuredProducts: ['p3', 'p7']
  }
];
